# Generated by Django 5.2.14 on 2026-05-30 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_timestamp', models.DateTimeField(auto_now_add=True)),
                ('quarter_processed', models.CharField(max_length=10, null=True)),
                ('table_name', models.CharField(max_length=50, null=True)),
                ('records_imported', models.IntegerField(default=0)),
                ('records_invalid', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('duration_seconds', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('error_message', models.TextField(null=True)),
            ],
            options={
                'db_table': 'pipeline_log',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('accession_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('filing_date', models.DateField(null=True)),
                ('issuer_cik', models.BigIntegerField(null=True)),
                ('issuer_name', models.CharField(max_length=255, null=True)),
                ('issuer_ticker', models.CharField(max_length=20, null=True)),
                ('rptowner_cik', models.BigIntegerField(null=True)),
                ('rptowner_name', models.CharField(max_length=255, null=True)),
                ('is_director', models.BooleanField(null=True)),
                ('is_officer', models.BooleanField(null=True)),
                ('is_ten_percent', models.BooleanField(null=True)),
                ('is_other', models.BooleanField(null=True)),
                ('officer_title', models.CharField(max_length=255, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('source_quarter', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'submissions',
                'indexes': [models.Index(fields=['issuer_cik'], name='idx_issuer_cik'), models.Index(fields=['source_quarter'], name='idx_sub_source_quarter'), models.Index(fields=['filing_date'], name='idx_filing_date')],
            },
        ),
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(max_length=30, null=True)),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.IntegerField(null=True)),
                ('check_name', models.CharField(max_length=100)),
                ('is_passed', models.BooleanField()),
                ('details', models.TextField(null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('source_quarter', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'validation_log',
                'indexes': [models.Index(fields=['accession_number'], name='idx_vlog_accession'), models.Index(fields=['source_quarter'], name='idx_vlog_source_quarter')],
            },
        ),
        migrations.CreateModel(
            name='NonderivTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField(null=True)),
                ('trans_code', models.CharField(max_length=5, null=True)),
                ('equity_swap', models.CharField(max_length=5, null=True)),
                ('shares', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('price_per_share', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('shares_owned_following', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('nominal_volume', models.DecimalField(decimal_places=4, max_digits=24, null=True)),
                ('is_valid', models.BooleanField(default=None, null=True)),
                ('validation_flags', models.CharField(default=None, max_length=500, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('source_quarter', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(db_column='accession_number', on_delete=django.db.models.deletion.CASCADE, related_name='nonderiv_trans', to='pipeline.submission')),
            ],
            options={
                'db_table': 'nonderiv_trans',
                'indexes': [models.Index(fields=['trans_code'], name='idx_nd_trans_code'), models.Index(fields=['trans_date'], name='idx_nd_trans_date'), models.Index(fields=['source_quarter'], name='idx_nd_source_quarter')],
            },
        ),
        migrations.CreateModel(
            name='NonderivHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares_owned', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('source_quarter', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(db_column='accession_number', on_delete=django.db.models.deletion.CASCADE, related_name='nonderiv_holdings', to='pipeline.submission')),
            ],
            options={
                'db_table': 'nonderiv_holdings',
                'indexes': [models.Index(fields=['source_quarter'], name='idx_ndh_source_quarter')],
            },
        ),
        migrations.CreateModel(
            name='DerivTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField(null=True)),
                ('trans_code', models.CharField(max_length=5, null=True)),
                ('equity_swap', models.CharField(max_length=5, null=True)),
                ('shares', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('price_per_share', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('shares_owned_following', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('nominal_volume', models.DecimalField(decimal_places=4, max_digits=24, null=True)),
                ('is_valid', models.BooleanField(default=None, null=True)),
                ('validation_flags', models.CharField(default=None, max_length=500, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('source_quarter', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(db_column='accession_number', on_delete=django.db.models.deletion.CASCADE, related_name='deriv_trans', to='pipeline.submission')),
            ],
            options={
                'db_table': 'deriv_trans',
                'indexes': [models.Index(fields=['trans_date'], name='idx_d_trans_date'), models.Index(fields=['source_quarter'], name='idx_d_source_quarter')],
            },
        ),
        migrations.CreateModel(
            name='DerivHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares_owned', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('source_quarter', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(db_column='accession_number', on_delete=django.db.models.deletion.CASCADE, related_name='deriv_holdings', to='pipeline.submission')),
            ],
            options={
                'db_table': 'deriv_holdings',
                'indexes': [models.Index(fields=['source_quarter'], name='idx_dh_source_quarter')],
            },
        ),
    ]
