"""
Django settings for secpipeline project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load the same .env the rest of the pipeline uses, so DB credentials
# live in exactly one place and never get hardcoded here.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key secret in production - set it via
# .env there. The fallback only exists so the test suite and the local
# SQLite setup run without an .env; this project has no web layer that
# actually relies on the key.
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-#*a@wt1g_epa=72u46ngbvr%cgu%1vbx0a3y5wyiat0kyp!cdt",
)

# SECURITY WARNING: don't run with debug on in production. Read from .env.
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = []


# Application definition

# This project uses Django purely as an ORM for the data pipeline -
# no web frontend, auth, or admin. Only contenttypes (the bare minimum
# the ORM relies on) plus our own app are enabled, which keeps the
# database free of unused auth/session/admin tables.
INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'pipeline',
]

# No middleware, templates, or URL routing - there is no web layer.
# Django is only here to manage the database schema and run queries.


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL is the intended target (the course server). For local
# development and the test suite there is a SQLite fallback: set
# DB_ENGINE to the sqlite3 backend in .env and the ORM plus the same
# migrations build an identical schema in a single local file - no
# server, no credentials. SQLite ignores host/user/password, so it only
# gets a file path under BASE_DIR; everything else stays the same.
DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.postgresql')

if DB_ENGINE.endswith('sqlite3'):
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': BASE_DIR / os.getenv('DB_NAME', 'local.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': os.getenv('DB_NAME', 'group01'),
            'USER': os.getenv('DB_USER', ''),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
